# Generated by Django 4.2.9 on 2024-01-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devtool', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default=1, max_length=1000, verbose_name='아이디어 설명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtool.devtool', verbose_name='예상 개발툴'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=24, verbose_name='아이디어명'),
        ),
    ]
