# Generated by Django 4.2.9 on 2024-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content_alter_post_devtool_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='아이디어 관심도'),
        ),
    ]
