# Generated by Django 4.2.9 on 2024-01-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devtool', '0001_initial'),
        ('posts', '0003_post_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devtool.devtool', verbose_name='예상 개발툴'),
        ),
    ]
