# Generated by Django 4.2.9 on 2024-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_heart_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heart_like',
            field=models.BooleanField(default=False),
        ),
    ]
