# Generated by Django 4.2.9 on 2024-01-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=24)),
                ('dev_type', models.CharField(max_length=24)),
                ('dev_content', models.CharField(max_length=24)),
            ],
        ),
    ]
