# Generated by Django 4.2.9 on 2024-01-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=32)),
                ('year_of_release', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=32)),
                ('score', models.CharField(max_length=32)),
                ('review_content', models.TextField()),
            ],
        ),
    ]
