# Generated by Django 4.2.9 on 2024-01-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_post_delete_review_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='actor',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='running_time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_year',
            field=models.TextField(),
        ),
    ]
